### ISSUE TITLE
Save your image

### ISSUE THREAD

**Issue by tnterdan** [tnterdan/wiggle#1]
Save images to a file. We can eventually have a basic file format that consists of `png` files as layers with a `yaml` file index inside a `zip` archive. But first we can just save the entire image to a `png`.

**Comment by avik-das** [comment]
Implemented. You can now save with `Ctrl+S`. Usability improvements would be nice, but the functionality is there.

Note that on Ubuntu, I get the following warning when popping up the file dialog for saving:

```
(python:18250): Gtk-WARNING **: Invalid input string
```

(The line number seems to change every execution.) I don't know what the issue is, but since everything works fine for now, I consider this implemented.
